name: lint

on: [push, pull_request]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Prettier
        run: yarn lint:prettier

      - name: ESLint
        run: yarn lint:eslint
